sonar.projectKey=boundless_boundless-be
sonar.organization=boundless

sonar.sources=api,controller,database,dto,errs,middleware,model,repository,service
sonar.tests=.

sonar.go.coverage.reportPaths=coverage.out
sonar.test.inclusions=**/*_test.go
sonar.exclusions=migrations/**,uploads/**,tmp/**,coverage.out,**/*_test.go
sonar.coverage.exclusions=main.go,database/**,service/document_storage_gcs.go,repository/dream_tracker_repository.go,service/dream_tracker_service.go,debug/**

sonar.sourceEncoding=UTF-8
