sonar.projectKey=boundless_boundless-be
sonar.organization=boundless

sonar.sources=api,controller,database,dto,errs,middleware,model,repository,service
sonar.tests=test

sonar.go.coverage.reportPaths=coverage.out
sonar.test.inclusions=test/**
sonar.exclusions=migrations/**,uploads/**,tmp/**,coverage.out
sonar.coverage.exclusions=main.go,database/**,service/document_storage_gcs.go

sonar.sourceEncoding=UTF-8
